wandb_version: 1

project_name:
  desc: null
  value: DCASE24_Task1
experiment_name:
  desc: null
  value: Baseline
num_workers:
  desc: null
  value: 0
precision:
  desc: null
  value: '32'
evaluate:
  desc: null
  value: false
ckpt_id:
  desc: null
  value: null
orig_sample_rate:
  desc: null
  value: 44100
subset:
  desc: null
  value: 5
n_classes:
  desc: null
  value: 10
in_channels:
  desc: null
  value: 1
base_channels:
  desc: null
  value: 32
channels_multiplier:
  desc: null
  value: 1.8
expansion_rate:
  desc: null
  value: 2.1
n_epochs:
  desc: null
  value: 150
batch_size:
  desc: null
  value: 256
mixstyle_p:
  desc: null
  value: 0.4
mixstyle_alpha:
  desc: null
  value: 0.3
weight_decay:
  desc: null
  value: 0.0001
roll_sec:
  desc: null
  value: 0.1
lr:
  desc: null
  value: 0.005
warmup_steps:
  desc: null
  value: 2000
sample_rate:
  desc: null
  value: 32000
window_length:
  desc: null
  value: 3072
hop_length:
  desc: null
  value: 500
n_fft:
  desc: null
  value: 4096
n_mels:
  desc: null
  value: 256
freqm:
  desc: null
  value: 48
timem:
  desc: null
  value: 0
f_min:
  desc: null
  value: 0
f_max:
  desc: null
  value: null
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.7
    framework: huggingface
    huggingface_version: 4.44.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1740464742
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      - 103
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      - 103
      3:
      - 7
      - 13
      - 15
      - 16
      - 19
      - 23
      - 66
      4: 3.10.14
      5: 0.17.7
      6: 4.44.0
      8:
      - 3
      - 5
      13: windows-amd64
    m:
    - 1: trainer/global_step
      6:
      - 3
MACs:
  desc: null
  value: 29419156
Parameters:
  desc: null
  value: 61148
